name: 'Vercel Deploy'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: '20'

jobs:
  # Simple build check for Vercel compatibility
  build-check:
    name: 'Build Check'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'apps/web/package-lock.json'
          
      - name: Install dependencies
        run: |
          cd apps/web
          npm ci --ignore-scripts
          
      - name: Build for production
        run: |
          cd apps/web
          npm run build
        env:
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: 1
          
      - name: Build success
        run: echo "✅ Build successful - ready for Vercel deployment!"